const extraVulnInfo = {
    heartbleed: "Dit is een kritieke fout waardoor aanvallers met extreem gemak informatie van uw websitebezoekers kunnen stelen. We raden u aan onmiddellijk contact op te nemen met uw serverbeheerder; dit is een extreem kritiek probleem!",
    dos: "Dit is een kritieke fout waardoor aanvallers gemakkelijk je website kunnen laten crashen, klanten kunnen mislopen en verdere aanvallen kunnen uitvoeren. We raden u aan onmiddellijk contact op te nemen met uw serverbeheerder; dit is een uiterst kritiek probleem!",
    ssl2: "Dit is een kritieke fout waardoor aanvallers met extreem gemak informatie van uw websitebezoekers kunnen stelen. We raden u aan onmiddellijk contact op te nemen met uw serverbeheerder; dit is een extreem kritiek probleem!",
    ssl3: "Dit is een kritieke fout waardoor aanvallers met extreem gemak informatie van uw websitebezoekers kunnen stelen. We raden u aan onmiddellijk contact op te nemen met uw serverbeheerder; dit is een extreem kritiek probleem!",
    tls0: "Dit is een kritieke fout waardoor aanvallers met extreem gemak informatie van uw websitebezoekers kunnen stelen. We raden u aan onmiddellijk contact op te nemen met uw serverbeheerder; dit is een extreem kritiek probleem!",
    tls1: "Dit is een kritieke fout waardoor aanvallers met extreem gemak informatie van uw websitebezoekers kunnen stelen. We raden u aan onmiddellijk contact op te nemen met uw serverbeheerder; dit is een extreem kritiek probleem!",
    tls2: "Hoewel dit geen kritieke fout is, raden we u sterk aan contact op te nemen met uw website- of serverbeheerder om te upgraden naar TLS 1.3 voor maximale beveiliging en compatibiliteit.",
    tls3: "Gefeliciteerd, je hebt de veiligste een meest recente vorm van verbindingsonderhandeling ingeschakeld!",
    Backup: "Dit is een kritieke fout die klantgegevens of bedrijfsinformatie kan blootleggen. We raden u aan onmiddellijk contact op te nemen met uw websitebeheerder!",
    "Weak Credentials": "Dit is een kritieke fout waardoor aanvallers gemakkelijk toegang kunnen krijgen tot je website en de inhoud kunnen beschadigen. We raden u aan onmiddellijk uw inloggegevens te veranderen!",
    "CLRF Injection": "Dit is een kritieke fout waardoor aanvallers gemakkelijk toegang kunnen krijgen tot je website en de inhoud kunnen beschadigen. We raden u aan onmiddellijk contact op te nemen met uw websitebeheerder!",
    "Content Security Policy Configuration": "Hoewel dit geen ernstige fout is, raden we je aan contact op te nemen met je websitebeheerder om CSP in te schakelen, vooral als je website kritieke of gevoelige informatie verwerkt.",
    "Cross Site Request Forgery": "Dit is een kritieke fout waardoor aanvallers de bezoekers van je website kunnen misleiden. We raden u ten zeerste aan contact op te nemen met uw websitebeheerder om dit probleem op te lossen!",
    "Potentially Dangerous File": "Er kan een gevoelig bestand op het internet staan. We raden u aan onmiddellijk contact op te nemen met uw websitebeheerder, omdat dit bestand klantgegevens of bedrijfsinformatie kan bevatten.",
    "Command Execution": "Dit is een kritieke fout waardoor aanvallers gemakkelijk toegang kunnen krijgen tot je website en de inhoud kunnen beschadigen. We raden u aan onmiddellijk contact op te nemen met uw websitebeheerder!",
    "Path Traversal": "Aanvallers kunnen bestanden blootleggen die niet goed zijn verborgen op uw website. We raden u aan onmiddellijk contact op te nemen met uw websitebeheerder, omdat dit bestand klantgegevens of bedrijfsinformatie kan bevatten.",
    "HTAccess Bypass": "Aanvallers kunnen bestanden blootleggen die niet goed zijn verborgen op uw website. We raden u aan onmiddellijk contact op te nemen met uw websitebeheerder, omdat dit bestand klantgegevens of bedrijfsinformatie kan bevatten.",
    "HTTP Secure Headers": "Uw website garandeert geen veilige verbinding. We raden u aan onmiddellijk contact op te nemen met uw server- of websitebeheerder om deze functionaliteit in te schakelen.",
    "Secure Flag Cookie": "Dit is een kritieke fout waarbij aanvallers mogelijk inloggegevens, vertrouwelijke bestanden en andere klantgegevens kunnen stelen. We raden u aan contact op te nemen met uw websitebeheerder om uw cookies onmiddellijk te beveiligen.",
    "HttpOnly Flag cookie": "Dit is een kritieke fout waarbij aanvallers mogelijk inloggegevens, vertrouwelijke bestanden en andere klantgegevens kunnen stelen. We raden u aan contact op te nemen met uw websitebeheerder om uw cookies onmiddellijk te beveiligen.",
    "Open Redirect": "Dit is een kritieke fout waarbij aanvallers zich als uw website kunnen voordoen, klantgegevens kunnen blootleggen en uw reputatie kunnen vernietigen. We raden je aan contact op te nemen met je websitebeheerder en deze redirect onmiddellijk te sluiten.",
    "SQL Injection": "Dit is een kritieke fout waardoor aanvallers gemakkelijk toegang kunnen krijgen tot je website en de inhoud kunnen beschadigen. We raden u aan onmiddellijk contact op te nemen met uw websitebeheerder!",
    "Server Side Request Forgery": "Aanvallers kunnen bestanden blootleggen die niet goed zijn verborgen op uw website. We raden u aan onmiddellijk contact op te nemen met uw websitebeheerder, omdat dit bestand klantgegevens of bedrijfsinformatie kan bevatten.",
    "Cross Site Scripting": "Dit is een kritieke fout waardoor aanvallers gemakkelijk toegang kunnen krijgen tot je website en de inhoud kunnen beschadigen. We raden u aan onmiddellijk contact op te nemen met uw websitebeheerder!",
    "XML External Entity": "Dit is een kritieke fout waardoor aanvallers gemakkelijk toegang kunnen krijgen tot je website en de inhoud kunnen beschadigen. We raden u aan onmiddellijk contact op te nemen met uw websitebeheerder!",
    "Internal Server Error": "",
    "Resource Consumption": "",
    "Fingerprint Web Technology": "",
};

module.exports = extraVulnInfo;
