const connectionVulnInfo = {
    heartbleed: "Heartbleed is een kwetsbaarheid in OpenSSL, software die wordt gebruikt om de communicatie tussen een apparaat van een gebruiker en een webserver te versleutelen (zoals wanneer je HTTPS ziet in de adresbalk van je webbrowser). Door deze bug kunnen aanvallers het geheugen lezen van de servers waarop kwetsbare versies van OpenSSL draaien. Dit geheugen kan gevoelige informatie bevatten, zoals privésleutels, gebruikersnamen, wachtwoorden en persoonlijke gegevens.",
    dos: "Bij een DOS-aanval overspoelt de aanvaller een server, website of netwerk met zoveel verkeer dat het beoogde systeem het niet aankan. Door deze overbelasting kan het systeem niet reageren op legitiem verkeer of wordt het aanzienlijk trager. Websites die kwetsbaar zijn voor DOS-aanvallen kunnen eenvoudig en met weinig moeite worden platgelegd!",
    ssl2: "SSL 2.0 is een extreem verouderde methode voor het beschermen van informatie die wordt verzonden tussen een website en zijn gebruikers. SSL 2.0 werd in 1996 stopgezet en is ongelooflijk kwetsbaar voor eenvoudige aanvallen. Zelfs eenvoudige aanvallers kunnen alle gebruikersinformatie stelen met deze extreem verouderde encryptiemethode!",
    ssl3: "SSL 3.0 brengt een hoog risico op inbreuken en gecompromitteerde gebruikersinformatie met zich mee vanwege de vele kwetsbaarheden. SSL 3.0 werd in 1999 stopgezet vanwege een enorme hoeveelheid veiligheidslekken die niet verholpen konden worden; deze fouten zijn fataal en extreem gevaarlijk voor gebruikers van uw website.",
    tls0: "TLS 1.0 is een andere extreem verouderde coderingsstandaard. Deze standaard werd formeel afgeschaft in 2021 en is absoluut niet veilig. Deze standaard was bedoeld om aanvallen van computers in 2006 af te weren en is dus absoluut niet in staat om aanvallen van moderne aanvallers af te weren. Alle gegevens die met TLS 1.0 naar een website worden verzonden, worden in alle opzichten volledig blootgesteld aan derden.",
    tls1: "TLS 1.1 is een andere extreem verouderde coderingsstandaard.  Deze standaard werd formeel afgeschaft in 2021 en is absoluut niet veilig. Deze encryptiestandaard is gebouwd om veilig te zijn tegen computers van voor 2012 en is absoluut niet meer verdedigbaar tegen moderne technologie. Alle informatie die naar een website wordt gestuurd met TLS 1.1 kan eenvoudig en snel worden gestolen door aanvallers; zelfs eenvoudige aanvallers zijn in staat om informatie te stelen voor websites die deze TLS-standaard gebruiken.",
    tls2: "TLS 1.2 is een relatief oude beveiligingsstandaard die actief wordt vervangen. Hoewel websites die TLS 1.2 gebruiken niet volledig onveilig zijn, maken technische fouten in de standaard het voor een aanvaller veel eenvoudiger om informatie te stelen in vergelijking met moderne beveiligingsstandaarden. Momenteel wordt TLS 1.2 vervangen door het veel bestendigere TLS 1.3 en wordt daarom beschouwd als een suboptimale beveiligingsstandaard.",
    tls3: "TLS 1.3 is de nieuwste encryptiestandaard die beschikbaar is. Alle gegevens die met TLS 1.3 worden verzonden, zijn beveiligd volgens de hoogste standaard en zijn beschermd tegen alle bekende aanvallen. TLS 1.3 zal de komende tien jaar in gebruik blijven en is dus een uitstekende keuze om informatie te beschermen die tussen uw website en zijn gebruikers wordt verzonden.",
};

module.exports = connectionVulnInfo;
